// <auto-generated />
using City_Easter_Eggs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace City_Easter_Eggs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("City_Easter_Eggs.Models.FavouritePoints", b =>
                {
                    b.Property<string>("FavoriteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PointId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FavoriteId");

                    b.HasIndex("PointId");

                    b.HasIndex("UserId");

                    b.ToTable("FavouritePoints");
                });

            modelBuilder.Entity("City_Easter_Eggs.Models.LikedPoints", b =>
                {
                    b.Property<string>("LikedId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PointId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LikedId");

                    b.HasIndex("PointId");

                    b.HasIndex("UserId");

                    b.ToTable("LikedPoints");
                });

            modelBuilder.Entity("City_Easter_Eggs.Models.PointOfInterest", b =>
                {
                    b.Property<string>("PointId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.HasKey("PointId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("POIs");
                });

            modelBuilder.Entity("City_Easter_Eggs.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LikesObtained")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("City_Easter_Eggs.Models.FavouritePoints", b =>
                {
                    b.HasOne("City_Easter_Eggs.Models.PointOfInterest", "Point")
                        .WithMany("FavoritedPoints")
                        .HasForeignKey("PointId");

                    b.HasOne("City_Easter_Eggs.Models.User", "User")
                        .WithMany("FavoritedPoints")
                        .HasForeignKey("UserId");

                    b.Navigation("Point");

                    b.Navigation("User");
                });

            modelBuilder.Entity("City_Easter_Eggs.Models.LikedPoints", b =>
                {
                    b.HasOne("City_Easter_Eggs.Models.PointOfInterest", "Point")
                        .WithMany("LikedPoints")
                        .HasForeignKey("PointId");

                    b.HasOne("City_Easter_Eggs.Models.User", "User")
                        .WithMany("LikedPoints")
                        .HasForeignKey("UserId");

                    b.Navigation("Point");

                    b.Navigation("User");
                });

            modelBuilder.Entity("City_Easter_Eggs.Models.PointOfInterest", b =>
                {
                    b.HasOne("City_Easter_Eggs.Models.User", "Creator")
                        .WithMany("PlacedPoints")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("City_Easter_Eggs.Models.PointOfInterest", b =>
                {
                    b.Navigation("FavoritedPoints");

                    b.Navigation("LikedPoints");
                });

            modelBuilder.Entity("City_Easter_Eggs.Models.User", b =>
                {
                    b.Navigation("FavoritedPoints");

                    b.Navigation("LikedPoints");

                    b.Navigation("PlacedPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
